version: "3.7"
services:
  app:
    image: ghcr.io/dae-boo/fastapi-server:latest
    container_name: docker-fastapi-deploy-server
    ports:
      - 3002:3002
    networks:
      - app

networks:
  app:
    driver: bridge